apiVersion: v1
kind: ConfigMap
metadata:
  name: rpg-ia-config
data:
  ENV: "production"
  API_HOST: "0.0.0.0"
  API_PORT: "8000"
  LLM_ENDPOINT: "http://vllm-service:8000/vllm/v1"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "rpgia"
  ALGORITHM: "HS256"
  REDIS_URL: "redis://redis:6379"